project:
  type: website
  output-dir: ../docs
  preview:
    port: 4200
  render: 
    - "*.qmd"
    - "!README.md"

website:
  title: "mrrobust"
  repo-url: https://github.com/remlapmot/mrrobust
  repo-branch: master
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: Examples
        menu:
          - text: "Examples from the helpfiles"
            href: examples/mrrobust-examples/index.qmd
          - text: "IJE article examples"
            href: examples/spiller-ije-2018-examples/index.qmd
          - text: "Using TwoSampleMR and mrrobust in a Stata Markdown document"
            href: examples/markstat-call-R-example/index.qmd
          - text: "Using TwoSampleMR and mrrobust in an R Markdown or Quarto document"
            href: examples/rmarkdown-call-stata-example/index.qmd
          - text: "Collecting and exporting results using `r(table)`"
            href: examples/save-estimates/index.qmd
          - text: "Fitting MVMR models"
            href: examples/mvcommands-example/index.qmd
      - text: Helpfiles
        menu:
          - text: "mrrobust"
            href: helpfiles/mrrobust-helpfile.html
          - text: "mr"
            href: helpfiles/mr-helpfile.html
          - text: "mrdeps"
            href: helpfiles/mrdeps-helpfile.html
          - text: "mregger"
            href: helpfiles/mregger-helpfile.html
          - text: "mreggerplot"
            href: helpfiles/mreggerplot-helpfile.html
          - text: "mreggersimex"
            href: helpfiles/mreggersimex-helpfile.html
          - text: "mrmedian"
            href: helpfiles/mrmedian-helpfile.html
          - text: "mrmedianobs"
            href: helpfiles/mrmedianobs-helpfile.html
          - text: "mrmodal"
            href: helpfiles/mrmodal-helpfile.html
          - text: "mrmodalplot"
            href: helpfiles/mrmodalplot-helpfile.html
          - text: "mrratio"
            href: helpfiles/mrratio-helpfile.html
          - text: "mrivests"
            href: helpfiles/mrivests-helpfile.html
          - text: "mrforest"
            href: helpfiles/mrforest-helpfile.html
          - text: "mrfunnel"
            href: helpfiles/mrfunnel-helpfile.html
          - text: "mrmvivw"
            href: helpfiles/mrmvivw-helpfile.html
          - text: "mrmvegger"
            href: helpfiles/mrmvegger-helpfile.html
          - text: "mrleaveoneout"
            href: helpfiles/mrleaveoneout-helpfile.html
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/remlapmot/mrrobust
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    highlight-style: arrow

# freeze: auto  # re-render only when source changes

bibliography: refs.bib
