project:
  type: website
  output-dir: ../docs

website:
  title: "mrrobust"
  repo-url: https://github.com/remlapmot/mrrobust
  repo-branch: master
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: Examples
        menu:
          - text: "Examples from the helpfiles"
            href: examples/mrrobust-examples.qmd
      - text: Helpfiles
        menu:
          - text: "mrrobust"
            href: mrrobust-helpfile.html
          - text: "mr"
            href: mr-helpfile.html
          - text: "mrdeps"
            href: mrdeps-helpfile.html
          - text: "mregger"
            href: mregger-helpfile.html
          - text: "mreggerplot"
            href: mreggerplot-helpfile.html
          - text: "mreggersimex"
            href: mreggersimex-helpfile.html
          - text: "mrmedian"
            href: mrmedian-helpfile.html
          - text: "mrmedianobs"
            href: mrmedianobs-helpfile.html
          - text: "mrmodal"
            href: mrmodal-helpfile.html
          - text: "mrmodalplot"
            href: mrmodalplot-helpfile.html
          - text: "mrratio"
            href: mrratio-helpfile.html
          - text: "mrivests"
            href: mrivests-helpfile.html
          - text: "mrforest"
            href: mrforest-helpfile.html
          - text: "mrfunnel"
            href: mrfunnel-helpfile.html
          - text: "mrmvivw"
            href: mrmvivw-helpfile.html
          - text: "mrmvegger"
            href: mrmvegger-helpfile.html
          - text: "mrleaveoneout"
            href: mrleaveoneout-helpfile.html
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/remlapmot/mrrobust
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
