project:
  type: website
  output-dir: ../docs

website:
  title: "mrrobust"
  repo-url: https://github.com/remlapmot/mrrobust
  repo-branch: master
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: examples.qmd
        text: Examples
      - href: helpfiles.qmd
        text: Helpfiles
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/remlapmot/mrrobust
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
